-- Supabase PostgreSQL Schema for Multi-Agent AI Travel Planner

-- Enable uuid-ossp extension
create extension if not exists "uuid-ossp";

-- 1. Users Table (tied to Supabase Auth)
create table public.users (
  id uuid references auth.users on delete cascade primary key,
  name text,
  email text unique,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for users
alter table public.users enable row level security;

create policy "Allow public read-only of profiles" 
  on public.users for select 
  using (true);

create policy "Allow users to update own profile" 
  on public.users for update 
  using (auth.uid() = id);

create policy "Allow users to insert own profile" 
  on public.users for insert 
  with check (auth.uid() = id);


-- 2. Trips Table (stores all agent details and itinerary data)
create table public.trips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade not null,
  destination text not null,
  budget numeric not null,
  start_date date not null,
  end_date date not null,
  travelers_count integer default 1 not null,
  preferences jsonb default '{}'::jsonb not null,
  status text default 'planning'::text not null,
  
  -- Outputs generated by Multi-Agent orchestrator
  destination_info jsonb,
  weather jsonb,
  flights jsonb,
  hotels jsonb,
  restaurants jsonb,
  local_transport jsonb,
  visa_info jsonb,
  currency_info jsonb,
  safety_tips jsonb,
  activities jsonb,
  packing_list jsonb,
  itinerary jsonb,
  budget_breakdown jsonb,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for trips
alter table public.trips enable row level security;

create policy "Users can view their own trips"
  on public.trips for select
  using (auth.uid() = user_id);

create policy "Users can insert their own trips"
  on public.trips for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own trips"
  on public.trips for update
  using (auth.uid() = user_id);

create policy "Users can delete their own trips"
  on public.trips for delete
  using (auth.uid() = user_id);


-- 3. Saved Trips / Favorites Table
create table public.saved_trips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade not null,
  trip_id uuid references public.trips(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, trip_id)
);

-- Enable RLS for saved_trips
alter table public.saved_trips enable row level security;

create policy "Users can view their own saved trips"
  on public.saved_trips for select
  using (auth.uid() = user_id);

create policy "Users can save trips"
  on public.saved_trips for insert
  with check (auth.uid() = user_id);

create policy "Users can unsave trips"
  on public.saved_trips for delete
  using (auth.uid() = user_id);


-- 4. Chat History Table (stores chat revisions)
create table public.chat_histories (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid references public.trips(id) on delete cascade not null,
  user_id uuid references public.users(id) on delete cascade not null,
  messages jsonb default '[]'::jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for chat_histories
alter table public.chat_histories enable row level security;

create policy "Users can view their own chat histories"
  on public.chat_histories for select
  using (auth.uid() = user_id);

create policy "Users can insert chat histories"
  on public.chat_histories for insert
  with check (auth.uid() = user_id);

create policy "Users can update their chat histories"
  on public.chat_histories for update
  using (auth.uid() = user_id);


-- Trigger to update 'updated_at' on trips modification
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger trips_updated_at
  before update on public.trips
  for each row
  execute procedure public.handle_updated_at();
